[build-system]
requires = ["setuptools>=45", "wheel", "oldest-supported-numpy", "scipy>=0.13.2", "setuptools_scm>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/osqp/_version.py"
